### PR TITLE
feat!: upgrade to ackee tracker 5 & more

### LINKED ISSUE #4: Upgrade to v5
[ackee-tracker v5](https://github.com/electerious/ackee-tracker)

[ackee-tracker v3](https://github.com/electerious/Ackee)

### LINKED ISSUE #8: trackerInstance and await
`trackerInstance ` isn't used https://github.com/bdrtsky/nuxt-ackee/blob/80306bed183551c113a72d756a60702235af7db1/lib/plugin.js#L3

There's no `await` https://github.com/bdrtsky/nuxt-ackee/blob/80306bed183551c113a72d756a60702235af7db1/lib/plugin.js#L5

### PR DESCRIPTION
**Pull request by lihbr**
Yo! Noticed there was [a cool update](https://github.com/electerious/Ackee/blob/master/CHANGELOG.md) bringing new things to Ackee, so I figured out I might help a bit~
Really happy to follow through if I need to address reviews of any sort ☺️ 

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### **`BREAKING`** Updated to [ackee-tracker@5](https://github.com/electerious/ackee-tracker/blob/master/CHANGELOG.md) cee1ae7
1. Used new `.create` syntax ([about](https://github.com/electerious/ackee-tracker/blob/master/CHANGELOG.md#new-create-syntax));
2. Used new `.record` syntax ([about](https://github.com/electerious/ackee-tracker/blob/master/CHANGELOG.md#new-record-syntax));
3. Closed existing record if necessary there's a previous one on route change ([about](https://github.com/electerious/ackee-tracker/blob/master/CHANGELOG.md#calling-record-again-wont-stop-running-record-updates)).

### **`NON-BREAKING`** New opt-in/opt-out modes for `options.detailed` 32bf48e, 7fce303

Ackee recommends enabling `detailed` mode after asking for user consent ([source](https://docs.ackee.electerious.com/#/docs/Anonymization#personal-data)). I implemented an easy way to ask for those through two new modes for `options.detailed`:
- `opt-in`: defaults to `detailed = false` except if user decides to opt-in
- `opt-out`: defaults to `detailed = true` except if user decides to opt-out (since detailed doesn't collect personal data regarding GDPR, why not, at least better than the current `detailed: true` most of us are using)
- `true/false`: keep their current behaviors

When `options.detailed` uses one of those two new modes a `details` object is injected inside `$ackee` (it isn't if using `true/false`):
- `value`: current status of the user, useful to know if we need to show a consent banner;
- `preference`: if user has defined a preference, useful to hide the consent banner;
- `unknown`: `true` when still on SSR, `false` once client plugin has loaded (similar to `nuxt-color-mode.unknown`);
- `optIn()`: opt-in users for sending details from now on, will set the configured key in local storage to `opted-in`;
- `optOut()`: opt-out users for sending details from now on, will set the configured key in local storage to `opted-out`.

A new option is also introduced: `options.storageKey`, it defaults to `nuxt-ackee` and is used with the two above functions.

### **`NON-BREAKING`** Minor Features & Quality of Life Improvements
4. Allowed `ignoreOwnVisits` option and reordered them for the sake of consistency 2448e58;
5. Delete the redundant `package-lock.json` and ignored it 9f40cd9;
6. Updated examples to check everything was working easily b3fb6d8, 487c2fb, 0c48430, 090804a;
7. Updated readme (I'll submit an other PR with a Nuxt content doc single page to normalize the module later on) 
04c80ab;
8. Updated test f4cbe49;
9. Fixes #8 c66907d.

### Remaining
- [ ] Update and publish package, I guess you'll handle that one~

Changes required to be compatible with the latest version of Ackee 🙂
Commits are following SemVer so changelog should be good!
Maintainers should have write access to my fork~

Cheers!

Resolves: #4

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly. (PR: #6)
- [x] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.
- [x] Works on Windows

### CODE REVIEW

**Comment by lihbr** [comment]
Just letting you know I'm done with updates ☺️

**Comment by productdevbook** [comment]
Wow, thank you :)

**Review by productdevbook — APPROVED** [review]

**Comment by vin-ni** [comment]
will this also support ACKEE_TRACKER=custom name ?

**Comment by lihbr** [comment]
No, this module is using ackee tracker as a NPM package, is doesn't even have to download something from your instance :)

**Pull request merged**
